---
title: "HW1"
author: "Kanke Sergey"
date: '26 декабря 2018 г '
output: html_document
---

```{r}
#Загрузите данные в датафрейм, который назовите data.df
data.df<-read.table("http://people.math.umass.edu/~anna/Stat597AFall2016/rnf6080.dat") 
#Сколько строк и столбцов в data.df?
#строки
nrow(data.df)
#столбцы
ncol(data.df)
#Получите имена колонок из data.df.
colnames(data.df)
#Найдите значение из 5 строки седьмого столбца.
data.df[5,7]
#Напечатайте целиком 2 строку из data.df
data.df[2,]
#Объясните, что делает следующая строка кода names(data.df) <- c("year", "month", "day", seq(0,23)).
names(data.df) <- c("year", "month", "day", seq(0,23))
colnames(data.df)
#ОТВЕТ: Задает имена для столбцов
##
#Воспользуйтесь функциями head и tail, чтобы просмотреть таблицу. Что представляют собой последние 24 колонки?
h<-head(data.df)
t<-tail(data.df)
#ОТВЕТ: последние 24 колонки скорее всего соответствуют осадкам по часам
##
#Добавьте новую колонку с названием daily, в которую запишите сумму крайних правых 24 колонок. Постройте гистограмму по этой колонке. Какие выводы можно сделать?
data.df$daily<-rowSums(data.df[,4:27])
hist(data.df$daily)
#Создайте новый датафрейм fixed.df в котром исправьте замеченную ошибку. Постройте новую гистограмму, поясните почему она более корректна.
fixed.df<-data.df
for(i in 1:nrow(fixed.df))
  for(j in 4:ncol(fixed.df))
    if(fixed.df[i,j]<0)
      fixed.df[i,j]<-0
hist(fixed.df$daily)
#ОТВЕТ: заменены отрицательные значения на 0
```


```{r}
#Для каждой строки кода поясните полученный результат, либо объясните почему она ошибочна.
v <- c("4", "8", "15", "16", "23", "42")
max(v)
#фунция выводит максимальное значение строки, но не числа
sort(v)
#фунция сортирует по элементам строк. Для чисел работает некорректно 
#sum(v)
#Error in sum(v) : invalid 'type' (character) of argument. Строки так не суммируются.
#Для следующих наборов команд поясните полученный результат, либо объясните почему они ошибочна.
v2 <- c("5",7,12)
#v2[2] + v2[3]
#Error in v2[2] + v2[3] : non-numeric argument to binary operator. Элементы вектора преобразованы к одному типу(chr)
df3 <- data.frame(z1="5",z2=7,z3=12)
df3[1,2] + df3[1,3]
#Работает корректно
l4 <- list(z1="6", z2=42, z3="49", z4=126)
l4[[2]] + l4[[4]]
#Работает корректно
#l4[2] + l4[4]
#Error in l4[2] + l4[4] : non-numeric argument to binary operator. Невозможно складывать таблицы 
```


```{r}
#Оператор двоеточие создаёт последовательность целых чисел по порядку. Этот оператор — частный случай функции seq(), которую вы использовали раньше. Изучите эту функцию, вызвав команду ?seq. Испольуя полученные знания выведите на экран:
#Числа от 1 до 10000 с инкрементом 372.
?seq
seq(1,1000, 372)
#Числа от 1 до 10000 длиной 50.
seq(1,10000, length.out = 50 )
#Функция rep() повторяет переданный вектор указанное число раз. Объясните разницу между rep(1:5,times=3) и rep(1:5, each=3).
rep(1:5,times=3) #Три раза повторяет последовательность
rep(1:5, each=3) #Три раза повторяет каждый элемент
```