---
title: "HW2"
author: "Kanke Sergey"
date: '26 декабря 2018 г '
output: html_document
---

```{r}
#агрузка и очистка данных
#Загрузите данные в датафрейм, который назовите data.
data<-read.csv("https://raw.githubusercontent.com/SergeyMirvoda/da2016/master/data/calif_penn_2011.csv",row.names=1)
```
```{r}
#Сколько строк и столбцов в data?
n<-nrow(data)
n#строк
ncol(data)#столбцов
```
```{r}
#Выполните следующую команду и объясните, что она делает. colSums(apply(data,c(1,2), is.na))
colSums(apply(data,c(1,2), is.na))
#Отображает количество NA значений в каждом столбце
```
```{r}
#Функция na.omit() принимает датафрейм и возвращает новый датафрейм, игнорируя строки, содержащие значение NA. Используйте эту функцию для удаления строк с неполными данными.
n.d<-na.omit(data)
#Сколько строк было удалено?
n-nrow(n.d)#удалено строк
```
```{r}
#Соответствует ли результат выполнения, значениям из пункта 3?
colSums(apply(n.d,c(1,2), is.na))
#Количество NA значений стало равно 0
```

```{r}
#Новые дома
#Переменная(колонка) Built_2005_or_later содержит данные о проценте домов, построенных с 2005 года. Постройте диаграмму рассеяния (scatterplot) медианы стоимости домов (переменная Median_house_value) относительно процента новых домов.

scatter.smooth(
  n.d$Built_2005_or_later ~ n.d$Median_house_value,
  ylab = "New Built",
  xlab = "Median house value"
)
```
```{r}
#Постройте ещё два графика для каждого из штатов отдельно. Номер штата содержится в переменной (STATEFP), где Калифорния 6-й штат, а Пенсильвания 42.
scatter.smooth(
  n.d$Built_2005_or_later[n.d$STATEFP == 6] ~ n.d$Median_house_value[n.d$STATEFP == 6],
  ylab = "New Built",
  xlab = "Median house value")
scatter.smooth(
  n.d$Built_2005_or_later[n.d$STATEFP == 42] ~ n.d$Median_house_value[n.d$STATEFP == 42],
  ylab = "New Built",
  xlab = "Median house value")
```
```{r}
# Незанятые дома
# Уровень найма (vacancy rate) — доля домов, которые не были заняты. В данных содержатся колонки, содержащие общее количество домовладений и количество не занятых домовладений.
# В датафрейм data добавьте новую колонку vacancy_rate, которая должна содержать вышеописанный показатель.
n.d$vacancy_rate <- n.d$Vacant_units/n.d$Total_units
# Найдите минимум, максимум, среднее и медиану полученных значений показателя.
min(n.d$vacancy_rate)
max(n.d$vacancy_rate)
mean(n.d$vacancy_rate)
median(n.d$vacancy_rate)
```
```{r}
# Постройте диаграмму уровня найма относительно медианы стоимости домов. Что можно заметить?
scatter.smooth(
  n.d$vacancy_rate ~ n.d$Median_house_value,
  ylab = "vacancy_rate",
  xlab = "Median house value")
#ОТВЕТ Можно заметить, что уровень найма выше, где медиана стоимости домов ниже
```
```{r}
# Корреляция
# Колонка COUNTYFP содержит числовой код округа внутри штата. Нас интересуют Butte County (округ 7 в Калифорнии), Santa Clara (округ 85 в Калифорнии) и York County (округ 133 в Пенсильвании).
# 
# Объясните, что делает приведённый в конце задания код и как именно он это делает.
acc <- c()
for (tract in 1:nrow(n.d)) {
  if (n.d$STATEFP[tract] == 6) {
    if (n.d$COUNTYFP[tract] == 1) {
      acc <- c(acc, tract)
    }
  }
}
accmv <- c()
for (tract in acc) {
  accmv <- c(accmv, n.d[tract,10])
}
median(accmv)
#считает медиану количества домовладений для STATEFP=6 и COUNTYFP=1

# Напишите другим способом в одну строку, то же самое, что делает нижеуказанный код. Способов получить тот же ответ множество, достаточно одного.
median(n.d$Total_units[n.d$STATEFP == 6][n.d$COUNTYFP == 1], na.rm = TRUE )
```

```{r}
# Найдите средний процент построенных домовладений в округах (Butte County, Santa Clara, York County)
mean(n.d$Total_units[n.d$STATEFP == 6 & n.d$COUNTYFP == 7] / sum(n.d$Total_units[n.d$STATEFP == 6 ]), na.rm = TRUE)
mean(n.d$Total_units[n.d$STATEFP == 6 & n.d$COUNTYFP == 85] / sum(n.d$Total_units[n.d$STATEFP == 6 ]), na.rm = TRUE)
mean(n.d$Total_units[n.d$STATEFP == 42 & n.d$COUNTYFP == 133] / sum(n.d$Total_units[n.d$STATEFP == 42]), na.rm = TRUE)
```
  
```{r}
# Функция cor рассчитывает коэффициент корреляции между двумя переменными. Рассчитайте корреляцию между медианы стоимости домовладений (Median_house_value) и процентом построенных домов (Built_2005_or_later):
# для всего набора данных
cor(as.numeric(n.d$Built_2005_or_later), n.d$Median_house_value)
# для Калифорнии
cor(as.numeric(n.d$Built_2005_or_later[n.d$STATEFP == 6]), n.d$Median_house_value[n.d$STATEFP == 6])
# для Пенсильвании
cor(as.numeric(n.d$Built_2005_or_later[n.d$STATEFP == 42]), n.d$Median_house_value[n.d$STATEFP == 42])
# для округа Butte County
cor(as.numeric(n.d$Built_2005_or_later[n.d$STATEFP == 6 & n.d$COUNTYFP == 7]), n.d$Median_house_value[n.d$STATEFP == 6 & n.d$COUNTYFP == 7], use = "pairwise.complete.obs")
# для округа Santa Clara
cor(as.numeric(n.d$Built_2005_or_later[n.d$STATEFP == 6 & n.d$COUNTYFP == 85]), n.d$Median_house_value[n.d$STATEFP == 6 & n.d$COUNTYFP == 85], use = "pairwise.complete.obs")
# для округа York County
cor(as.numeric(n.d$Built_2005_or_later[n.d$STATEFP == 42 & n.d$COUNTYFP == 133]), n.d$Median_house_value[n.d$STATEFP == 42 & n.d$COUNTYFP == 133], use = "pairwise.complete.obs")
# Постройте три диаграммы медианы стоимости домовладений (Median_house_value) относительно медианы дохода (Median_household_income) для трёх округов. Допустимо указать все три на одном графике.
# Код
plot(n.d$Median_house_value[n.d$STATEFP == 6 & n.d$COUNTYFP == 7] ~ n.d$Median_household_income[n.d$STATEFP == 6 & n.d$COUNTYFP == 7])
plot(n.d$Median_house_value[n.d$STATEFP == 6 & n.d$COUNTYFP == 85] ~ n.d$Median_household_income[n.d$STATEFP == 6 & n.d$COUNTYFP == 85])
plot(n.d$Median_house_value[n.d$STATEFP == 42 & n.d$COUNTYFP == 133] ~ n.d$Median_household_income[n.d$STATEFP == 42 & n.d$COUNTYFP == 133])
```


