---
title: "Lab 4"
author: "Kanke Sergey"
date: '26 декабря 2018 г '
output: html_document
---
```{r}
#Пользуясь примером из лекции файл (5.0.R) проанализируйте данные
#о возрасте и физ. характеристиках молюсков
#https://archive.ics.uci.edu/ml/datasets/abalone
data <- read.csv("https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data", header=TRUE, sep=",")
summary(data)
colnames(data)
colnames(data) <- c("sex", "length", "diameter", "height", 
                "whole_weight", "shucked_weight",
                "viscera_weight", "shell_weight", "rings")

colnames(data)
data$sex <- factor(c("Female", "Infant", "Male")[data$sex])
par(mfrow=c(1,3)) 
hist(data$diameter, main = "Диаметр, мм")
hist(data$height, main = "Высота, мм")
hist(data$whole_weight, main = "Полный вес, гр")
#Видим ассиметрию https://en.wikipedia.org/wiki/Skewness
```
```{r}
#Визулизируем возможные зависимости
par(mfrow=c(1,2)) 
plot(data$diameter, data$whole_weight,'p',main = "Зависимость веса от диаметра")
plot(data$height, data$whole_weight,'p',main = "Зависимость веса от высоты")
```
```{r}
#избавление от выбросов
data.new <- data[data$height < 0.4,]
plot(data.new$height, data.new$whole_weight,'p',main = "Зависимость веса от высоты")
#Хорошо видна зависимость, нужно её исследовать
```
```{r}
#построить линейные модели при помощи функции lm, посмотреть их характеристики
linear.model.1 <- lm (diameter ~ whole_weight, data=data.new)
linear.model.1
summary(linear.model.1)
plot(linear.model.1)
```
```{r}
linear.model.2 <- lm (height ~ whole_weight, data=data.new)
linear.model.2
summary(linear.model.1)
plot(linear.model.2)
```
```{r}
#разделить массив данных на 2 случайные части
odds <- seq(1, nrow(data.new), by=2)
data.in <- data.new[odds,]
data.out <- data.new[-odds,]
linear.model.half <- lm (rings ~ . - length, data=data.in)
summary (linear.model.half)
#подогнать модель по первой части
data.predict <- predict (linear.model.half)
cor (data.in$length, data.predict)
plot (data.in$length, data.predict)
#спрогнозировать (функция predict) значения во второй части
data.predict.out <- predict (linear.model.half, data.out)
#проверить качесвто прогноза
cor (data.out$length, data.predict.out)
plot (data.out$length, data.predict.out)
```